name: Deploy Dev Application

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Default
    env:
      # Secrets
      BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
      AUTH_GOOGLE_ID: ${{ secrets.AUTH_GOOGLE_ID }}
      AUTH_GOOGLE_SECRET: ${{ secrets.AUTH_GOOGLE_SECRET }}
      TMDB_BEARER_TOKEN: ${{ secrets.TMDB_BEARER_TOKEN }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Vars
      BETTER_AUTH_URL: ${{ vars.BETTER_AUTH_URL_DEV }}
      NEXT_PUBLIC_API_URL: ${{ vars.BETTER_AUTH_URL_DEV }}
      BETTER_AUTH_SESSION_CACHE: ${{ vars.BETTER_AUTH_SESSION_CACHE }}
      BETTER_AUTH_RATE_LIMIT: ${{ vars.BETTER_AUTH_RATE_LIMIT }}

      # Vercel
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_DEV }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel
        run: npx vercel --prod --token="$VERCEL_TOKEN" --confirm
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_DEV }}
